pundit-app/config/routes.rb
Rails.application.routes.draw do
  #resources :ads #, path: :advertisements
  # namespace :message do
  #   resources :messages
  # end
  # scope :message do
  #   resources :messages
  # end
  resources :inboxes do
  #  namespace :message do
    resources :messages, path: :msgs
 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

pundit-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pundit-app/app/models/inbox.rb
class Inbox < ApplicationRecord
  has_many :messages
end

pundit-app/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :inbox
end

pundit-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

pundit-app/app/controllers/inboxes_controller.rb
class InboxesController < ApplicationController
  before_action :set_inbox, only: %i[ show edit update destroy ]

  # GET /inboxes or /inboxes.json
  def index
    @inboxes = Inbox.all
    render json:@inboxes
  end

  # GET /inboxes/1 or /inboxes/1.json
  def show
    render json:@inbox
  end

  # GET /inboxes/new
  def new
    @inbox = Inbox.new
  end

  # GET /inboxes/1/edit
  def edit
  end

  # POST /inboxes or /inboxes.json
  def create
    @inbox = Inbox.new(inbox_params)

    respond_to do |format|
      if @inbox.save
        format.html { redirect_to inbox_url(@inbox), notice: "Inbox was successfully created." }
        format.json { render :show, status: :created, location: @inbox }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inboxes/1 or /inboxes/1.json
  def update
    respond_to do |format|
      if @inbox.update(inbox_params)
        format.html { redirect_to inbox_url(@inbox), notice: "Inbox was successfully updated." }
        format.json { render :show, status: :ok, location: @inbox }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inboxes/1 or /inboxes/1.json
  def destroy
    @inbox.destroy

    respond_to do |format|
      format.html { redirect_to inboxes_url, notice: "Inbox was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inbox
      @inbox = Inbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inbox_params
      params.require(:inbox).permit(:title)
    end
end

pundit-app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_inbox, only: %i[index show edit update destroy ]
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index

    render json:@inbox.messages
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message=@inbox.messages.build
    #@message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message=@inbox.messages.build(message_params)
    #@message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to [@inbox,@message], notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to [@inbox, :messages], notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_inbox 
      @inbox=Inbox.find(params[:inbox_id])
    end 
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:title)
    end
end

pundit-app/app/helpers/application_helper.rb
module ApplicationHelper
end

pundit-app/app/helpers/inboxes_helper.rb
module InboxesHelper
end

pundit-app/app/helpers/messages_helper.rb
module MessagesHelper
end

pundit-app/app/views/inboxes/_form.html.erb
<%= form_with(model: inbox, local: true) do |form| %>
  <% if inbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inbox.errors.count, "error") %> prohibited this inbox from being saved:</h2>

      <ul>
      <% inbox.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pundit-app/app/views/inboxes/edit.html.erb
<h1>Editing Inbox</h1>

<%= render 'form', inbox: @inbox %>

<%= link_to 'Show', @inbox %> |
<%= link_to 'Back', inboxes_path %>

pundit-app/app/views/inboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inboxes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inboxes.each do |inbox| %>
      <tr>
        <td><%= inbox.title %></td>
        <td><%= link_to 'Show', inbox %></td>
        <td><%= link_to 'Edit', edit_inbox_path(inbox) %></td>
        <td><%= link_to 'Destroy', inbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inbox', new_inbox_path %>

pundit-app/app/views/inboxes/new.html.erb
<h1>New Inbox</h1>

<%= render 'form', inbox: @inbox %>

<%= link_to 'Back', inboxes_path %>

pundit-app/app/views/inboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @inbox.title %>
</p>

<%= link_to 'Edit', edit_inbox_path(@inbox) %> |
<%= link_to 'Back', inboxes_path %>

pundit-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PunditApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

pundit-app/app/views/messages/_form.html.erb
<%= form_with(model: [@inbox,message], local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

pundit-app/app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

pundit-app/app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Inbox</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.title %></td>
        <td><%= message.inbox %></td>
        <td><%= link_to 'Show', inbox_messages_path %></td>
        
        <td><%= link_to 'Destroy', [@inbox,@message], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_inbox_message_path %>

pundit-app/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', inbox_messages_path(@inbox) %>

pundit-app/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Inbox:</strong>
  <%= @message.inbox %>
</p>

<%= link_to 'Edit', edit_inbox_message_path([@inbox,@message]) %> |
<%= link_to 'Back', [@inbox,@messages] %>